### ISSUE TITLE
Reconnection

### ISSUE THREAD

**Issue by Teraqz** [cpieprzak/PoeAggregator#1]
Anyone got issue with reconnection when it's taking too long to restore all connected sockets?
Looking at console logs you can see that webSocketWrapper.js is always trying to connect, but i guess poe trade api will just deny that, and that could be for like 2-3 minutes, where you have 0 sockets connected out of your total pool.
So it's entire api's fault that this is happening?

**Comment by cpieprzak** [comment]
It throws error codes when the sockets disconnect, and appears to take a while before they can reconnect.  They throw various codes (1006,1008) but it doesn't really seem to follow any pattern.
