### ISSUE TITLE
PoeAgg stopped working

### ISSUE THREAD

**Issue by encorep** [cpieprzak/PoeAggregator#12]
Unfortunately the program stopped working completely. Seems like its just not displaying any search results anymore. (Btw amazing program)

**Comment by ThilleFisch** [comment]
Yes, same for me... like 5 days ago, PoE changed something internally and now also added a rate limit. This causes the sockets to not connect even if refreshing PoEsessionID. A similar program (5k mirrors) encountered the identical problem. The creator published a fix today, but I like this program much more!
Would really appreciate a fix!  <3

**Comment by ikelso** [comment]
It looks like GGG is requiring a user-agent string to be passed with the websocket request.

		this.socket = new WebSocket(
				this.url,
			    [],
			    {
			    	'origin' : 'https://www.pathofexile.com/',
			        'headers': 
			        {
						'Cookie': cookie.serialize('POESESSID', poesessionid)
						**'User-Agent': 'PoeAggregator'**
			        }
			    }
			);

Adding that user-agent string allows my websockets to connect.  It would probably be best to add a dynamic version variable to that user agent as well so that GGG can identify if/when outdated versions are causing issues.  They can likely filter requests on their side by user-agent and deny all the old version traffic.

**Comment by ikelso** [comment]
Created [This PR](https://github.com/cpieprzak/PoeAggregator/pull/13) to resolve this issue.  Hopefully the owner can review it and accept or make his/her own changes.

**Comment by ThilleFisch** [comment]
Thanks ikelso for looking into this!
I hope cpieprzak looks into this soon / approves your PR. Until then, is there anyway to already use your version?

**Comment by ikelso** [comment]
Yes, if you're familiar with git and npm/node.  

You can clone my fork at https://github.com/ikelso/PoeAggregator

then run npm install
then npm run dist

dist will package the code up into an executable in the dist/ directory.  You can run the program from the .exe there.

**Comment by ThilleFisch** [comment]
Nice!
I'm not too familiar with programmign / github, but luckily a friend of mine is and he created the .exe for me  :)

Thank you so much for your contribution  <3

**Comment by gayanj** [comment]
> 
> 
> It looks like GGG is requiring a user-agent string to be passed with the websocket request.
> 
> ```
> 	this.socket = new WebSocket(
> 			this.url,
> 		    [],
> 		    {
> 		    	'origin' : 'https://www.pathofexile.com/',
> 		        'headers': 
> 		        {
> 					'Cookie': cookie.serialize('POESESSID', poesessionid)
> 					'User-Agent': 'PoeAggregator'
> 		        }
> 		    }
> 		);
> ```
> 
> Adding that user-agent string allows my websockets to connect. It would probably be best to add a dynamic version variable to that user agent as well so that GGG can identify if/when outdated versions are causing issues. They can likely filter requests on their side by user-agent and deny all the old version traffic.

This works! Thank you so much! :)

**Comment by H0TC0FFEE** [comment]
Could you upload a working exe file?
I would be very grateful as I do not understand anything in npm.

**Comment by ikelso** [comment]
https://github.com/ikelso/PoeAggregator/releases/tag/2.1.6

I've made a release on my github for you.

**Comment by H0TC0FFEE** [comment]
Big Thanks <3

**Comment by cpieprzak** [comment]
This is fixed.
