### ISSUE TITLE
Web Sockets not connecting

### ISSUE THREAD

**Issue by guifa11** [cpieprzak/PoeAggregator#2]
Hey, thanks for making/updating PoeAggregator! Its really useful. 
I am having problem trying to connecting the Open Sockets, i was using the program without any problem for a week but yesterday and today i am having problems with the websockets, there is any solution on how to fix that?

**Comment by cpieprzak** [comment]
One thing to check is whether you have been logged out of the official trade website.  The tool cannot connect if you are not logged in.  (I should probably have something that gives you a message if your not, but I'll get to it when I can.
