### ISSUE TITLE
copying whisper message

### ISSUE THREAD

**Issue by ShrekIII** [cpieprzak/PoeAggregator#26]
At least for me the whisper message if a wanted trade is found won't be copied automatically to the clipboard.
(I already checked the checkbox in the settings menu)

**Comment by cpieprzak** [comment]
To clarify, your having an issue where the Auto-copy checkbox is checked for a search, yet when an item shows up in the live search it is not copied to the clipboard.  Is that correct?

**Comment by cpieprzak** [comment]
Closing issue, as it does not appear to be reproducible.
