### ISSUE TITLE
Price filter not always working

### ISSUE THREAD

**Issue by thatguy692** [cpieprzak/PoeAggregator#27]
I've been using this tool for 2 leagues now, and there's something i don't understand.
When i set a max price of 60c for an item,  somehow i'm still seeing results for that item with a higher price. Why is that the case ?

**Comment by cpieprzak** [comment]
"When i set a max price of 60c for an item" => I assume you mean you create a search on their website with 60c as the max buyout price.

This can happen when someone changes the price of the item in between when you get a hit from the live search and when the aggregator looks up the actual info corresponding to the id returned by the live search.
