### ISSUE TITLE
Not connecting to Official API.

### ISSUE THREAD

**Issue by acidreian666** [cpieprzak/PoeAggregator#3]
So it was working perfect for weeks. Last night i pressed Stop on the live search. I started pressed start this morning and it hasn't been able to connect sense.
Using the console on Chromes Debug it looks like its not connecting to the API search Query

`poeaggregator.html:1 Access to XMLHttpRequest at 'https://www.pathofexile.com/api/trade/fetch/?query=' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

`main.js:137 GET https://www.pathofexile.com/api/trade/fetch/?query= net::ERR_FAILED`

pathofexile.com trade might be officially blocking the web-socket?

I read the last 2 previous Issues which are identical, The issue is I have used 3 pc's 3 accounts and 3 web browsers resulting same issue.

**Comment by cpieprzak** [comment]
This is a different issue from the previous issues.  Either the browser you are using stopped sending cookies without the 'Access-Control-Allow-Origin' field, or GGG updated how they set their cookies. Not sure, investigating.  Let me know what browser your using.

**Comment by acidreian666** [comment]
I have used Chrome, Internet explorer 11, Edge, Firefox. all have worked in the past.
But none of them work now.
My friend & I both normally Use Chrome & we both have the exact same issue I don't think we are the only ones.

**Comment by plamenzhl** [comment]
Hello! Just wanted to say that me and a couple of friends have the same issue as described above.

**Comment by howdoibinggoogle** [comment]
GGG has changed stuff on their end, some other programs are having the same/similar issues.

**Comment by acidreian666** [comment]
> GGG has changed stuff on their end, some other programs are having the same/similar issues.

Which programs is similarly having issues?

**Comment by acidreian666** [comment]
@cpieprzak Is Aggregator working for you?

**Comment by cpieprzak** [comment]
Depends on how you use it.  You can no run it through a browser.  Additionally, GGG has added a 20 connection limit to how many web sockets you have open, presumably so that they can handle a reasonable amount of load.

**Comment by cpieprzak** [comment]
I am working on a way to deploy it, but its going to take a while.

**Comment by acidreian666** [comment]
> I am working on a way to deploy it, but its going to take a while.

So if you wanna look through some of the java code on this.
https://greasyfork.org/en/scripts/387586-poe-trade-enhancer

Thats what i been using as a work around for the problems with aggregator.
but the downside is its super slow very buggy.
if you did something similar that removes all the bs so the bandwidth drops and has the features it would be perfect.

**Comment by cpieprzak** [comment]
What this is doing (javascript not java btw) is modifying the html page you get back from going to a website (poe.trade or the official trade website) and inserting their code into that page.  This works because when you send requests from that page, it sends all the cookies (including the cookie that identifies you as you) to the site.  The problem with this is that you need to be a bit skeptical of these tools, as they could additionally send this identifying information elsewhere.

**Comment by acidreian666** [comment]
There is also 5K-mirror's poe Live search manager which is a actual desktop program that works flawlessly with the official trade sites live search its just lacking all the features your aggregator does.

**Comment by cpieprzak** [comment]
Indeed. I am currently writing a desktop application that will allow you to connect.  Unfortunately, you will have to provide some method to authenticate (probably sessionid, but maybe have the option for username and password). Going to be a bit though.

**Comment by cpieprzak** [comment]
Electron version of app almost up.

**Comment by cpieprzak** [comment]
New version released.  Can be viewed and downloaded by navigating to https://github.com/cpieprzak/PoeAggregator/releases
