### ISSUE TITLE
Auto Copy to clipboard?

### ISSUE THREAD

**Issue by luxus** [cpieprzak/PoeAggregator#4]
Can u add a option per item that it can get added to the clipboard, so i can just paste when i hear a specific sound for very important items

**Comment by cpieprzak** [comment]
Yeah, I could probably add a checkbox per search.

**Comment by cpieprzak** [comment]
Checkbox added to search menu.
https://github.com/cpieprzak/PoeAggregator/releases/tag/v2.0.0

**Comment by luxus** [comment]
thanks!
