### ISSUE TITLE
[enhance] about limitations

### ISSUE THREAD

**Issue by 0ldi** [cpieprzak/PoeAggregator#7]
And another question if you do not mind about limitations. As I understand it, 20 active searches per 1 poesessionid. But 20 I think is not enough even for an ordinary player at the start of the league, especially about active hard-flippers.
Suppose I have another PoE-accound, so there is an additional poesessionid. But the catch is that the App saves (littering, as modern users portable apps call it) in the directories:
\Roaming\PoeAggregator
The best solution would be to split your releases into:
-common version (for casual users)
-portable version (for smart pepegas) that saves the app to where unpack it, and not garbage in:
\Local\Programs\PoeAggregator
'+ saves settings in the same directory.
Not sure if this will help run 20*poesessionid of active searches, but portable versions users will definitely like it.
If it doesn’t need a lot of work, I hope.

**Comment by cpieprzak** [comment]
Only 20 can be active by IP.
